#!/bin/zsh

echo "
fd	: cd to selected directory
fda	: cd to selected directory (including hidden directories)
fopen	: Open selected directory with finder
fvim	: Modified the file with vim
fcode	: Modified the file with vscode
fif	: grep [word] -> echo filename
fh	: repeat history
fz	: Select directory (z search)
fkill	: kill process
fadd	: Interactive git add
fbr	: checkout git branch (including remote branches), sorted by most recent commit
fco	: checkout git branch/tag, with a preview showing the commits between the tag/branch and HEAD
fshow	: git commit browser with previews
fcs	: Get git commit sha
cdtree	: Select a git worktree
da	: Select a docker container to start and attach to
ds	: Select a running docker container to stop
drm	: Select a docker container to remove
drmi	: Select a docker image or images to remove
"
